[Settings]
# Which SQL driver should the rank system be running on? Write either 'sqlite' or 'mysql'
# If you choose it to run on a 'sqlite' driver, it will create a local DB in `amxmodx/data/sqlite3` with name `RanksUltimate.sq3`.
# Choosing 'mysql' will retrieve the MySQL details from the `amxmodx/configs/sql.cfg` file, namely the host, user, pass and db.
# The tables names created in both DB will always be the following: `rank_system_new`, `weapon_kills_new` and `zp_stats` if you run the system on ZP Mode.
SQL_DRIVER = sqlite

# What language to appear the MOTDs by default?
# List of all languages: en (English), de (German), sr (Serbian), tr (Turkish), fr (French), sv (Swedish), da (Danish), pl (Polish), nl (Dutch), es (Spanish), bp (Brazilian Portuguese), cz (Czech), fi (Finnish), bg (Bulgarian), ro (Romanian), hu (Hungarian), lt (Lithuanian), sk (Slovak), mk (Macedonian), hr (Croatian), bs (Bosnian), ru (Russian), cn (Simplified Chinese), al (Albanian), pt (European Portuguese)
# Leave blank if you want the language to depend on the player's personal language, chosen from amx_langmenu.
MOTD_LANGUAGE =

# What to save the data by? (0 = save by name | 1 = save by IP | 2 = save by SteamID)
SAVE_TYPE = 0

# When to save the data? (0 = save on round end | 1 = save on map end)
# Value, greater than 1 will result in saving the data every 'x' minutes set accordingly.
SAVE_INTERVAL = 0

# The chat prefix for every chat messages. ($1 = normal color | $3 = team color | $4 = green color)
CHAT_PREFIX = $4[ANORMALII.COM]$1

# Shows information about the player's rank on each spawn. Like how many ranks he got up/down or if he's logged in/out the Top 15. (0 = off | 1 = on)
RANK_INFO = 1

# Enable/Disable bots ranking. Set to '2' if you want do disable bots ranking but keep real players from receiving statistics from them.
RANK_BOTS = 0

# For how long a player is considered new (in seconds).
TIME_NEW = 7200

# How to order the top players by default.
# Statistics in brackets will take place if the system runs on ZP mode.
# First value defines the default stats order: 0 = XP | 1 = Nick | 2 = Kills | 3 = Assists | 4 = Deaths | 5 = Skill | 6 = HS % | 7 = Bombs Planted (Human Wins) | 8 = Bombs Exploded (Infections) | 9 = Bombs Defused (Survivals) | 10 = Rounds Won (Zombie Wins) | 11 = MVP | 12 = Rank | 13 = Overall | 14 = Weapon
# Second value defines the default weapon order that will be displayed in top15: 0 = Knife | 1 = Glock18 | 2 = USP | 3 = P228 | 4 = Deagle | 5 = Fiveseven | 6 = Elite | 7 = M3 | 8 = XM1014 | 9 = TMP | 10 = MAC10 | 11 = MP5 Navy | 12 = UMP45 | 13 = P90 | 14 = M249 | 15 = Galil | 16 = Famas | 17 = AK47 | 18 = M4A1 | 19 = SG552 | 20 = AUG | 21 = Scout | 22 = AWP | 23 = G3SG1 | 24 = SG550 | 25 = HE Grenade
DEFAULT_ORDER = 13 0

# If the first value is greater than 0, players will not receive certain statistics, determined from the second value, unless there are at least 'X' amount of players connected to the server.
# Statistics in the second value are separated with the symbol '|' (if more than one) and WITHOUT spaces. They are the following (statistics in brackets will take place if the system runs on ZP mode): all, level, kills, assists, deaths, headshots, planted (humaniwins), defused (survivals), exploded (infections), roundswon (zombiewins), mvp, shots, hits, damage
MINIMUM_PLAYERS = 0 level

# Which team should receive XP (0/blank = All Teams | 1 = Terrorists Only | 2 = CT Only | 3 = Spectators Only)
TEAM_SET =

# Whether or not to show the Map End MOTD screen. (0 = Hide | 1 = Show)
SHOW_MAPEND_MOTD = 1

# Enable/Disable player's HUD rank status. (0 = off | 1 = on)
HUD_ENABLE = 1

# HUD type if HUD_ENABLE is 1. (0 = HUD | 1 = DHUD)
HUD_TYPE = 0

# HUD information about the player's rank status.
# You can use the following replacements: %newline%, %name%, %xp%, %xp_percent%, %%, %level%, %rank%, %next_xp%, %next_level%, %next_rank%, %max_levels%, %server_rank%, %max_server_ranks%, %minutes%, %seconds%, %skill%, %skill_range%, %next_skill%, %next_skill_range%
# Note: For the symbol '%' to work, you need to type it twice '%%'
# Maximum length info is 512 characters.
HUD_INFO = Name: %name% %newline%Level: %level% / %max_levels% %newline%XP: %xp% / %next_xp% (%xp_percent%%%) %newline%Rank: %rank% %newline%Server Rank: %server_rank% / %max_server_ranks% %newline%Skill: [%skill% %skill_range%]

# HUD information about the player's rank status if he's reached the maximum level.
HUD_INFO_MAX = Name: %name% %newline%Level: %level% %newline%XP: %xp% %newline%Rank: %rank% %newline%Server Rank: %server_rank% / %max_server_ranks% %newline%Skill: [%skill% %skill_range%]

# HUD values. Use -1 for random color. Use -1.0 in positions for center.
# Values:    Red     Green     Blue     Position X     Position Y
HUD_VALUES = 0 	     255 	   -1		0.01	       0.17

# Message type when a player levels up/down (0 = turn off | 1 = only he can see it | 2 = all players can see it) 
LEVEL_MESSAGE_TYPE = 2

# Level up screen effects. Use -1 for random color. To disable effects, change the value of 'Alpha' to 0.
# Values: 	  	  Red     Green     Blue     Alpha     Hold time
LEVELUP_EFFECTS = 0       255       0        75        1.0

# Level up sound (leave blank for no sound).
LEVELUP_SOUND = warcraft3/levelupcaster.wav

# Level down screen effects. Use -1 for random color. To disable effects, change the value of 'Alpha' to 0.
# Values: 	  	  Red     Green     Blue     Alpha     Hold time
LEVELDN_EFFECTS = 255     0         0        75        1.0

# Level down sound (leave blank for no sound).
LEVELDN_SOUND = warcraft3/purgetarget1.wav

# Assists values which are minimum damage required in order for an assist to count, how much money the assistant gets and whether or not the assistant to receive a frag.
# Values: 		Minimum Damage     Money     Receive Frag
ASSIST_VALUES = 40                 50       1

# Enable/Disable HUD message when you/your team gets/loses XP. (0 = off | 1 = on)
XP_HUD_ENABLE = 1
XP_HUD_TEAM_ENABLE = 1

# HUD type if XP_HUD_ENABLE is 1. (0 = HUD | 1 = DHUD)
XP_HUD_TYPE = 1
XP_HUD_TEAM_TYPE = 1

# HUD message when getting XP.
XP_HUD_GET = +%xp% XP
XP_HUD_TEAM_GET = +%xp% Team XP

# HUD message when losing XP.
XP_HUD_LOSE = -%xp% XP
XP_HUD_TEAM_LOSE = -%xp% Team XP

# HUD values. Use -1 for random color. Use -1.0 in positions for center.
# Effect notes: 0 = no effect | 1 = blinking | 2 = typewriter
# Values:     	     Red     Green     Blue     Position X     Position Y     Effect     Hold time
XP_HUD_VALUES =      0       255       150  	0.65	       0.70 	      0          1.0
XP_HUD_TEAM_VALUES = 0       255       150     	0.65	       0.75 	      0          1.0

# Enable/Disable HUD message for end round MVP. (0 = off | 1 = on)
MVP_HUD_ENABLE = 1

# HUD type if MVP_HUD_ENABLE is 1. (0 = HUD | 1 = DHUD)
MVP_HUD_TYPE = 0

# HUD values. Use -1 for random color. Use -1.0 in positions for center.
# Values:     	 Red     Green     Blue     Position X     Position Y 
MVP_HUD_VALUES = 150     150       150  	-1.0	       0.15

[Commands]
# Top commands. DON'T include the number at the end. (eg. /top15, /top45, /top50 etc.)
TOP_COMMANDS = say /top, say_team /top

# Bot commands. DON'T include the number at the end. (eg. /bot15, /bot45, /bot50 etc.)
BOT_COMMANDS = say /bot, say_team /bot

# Topfind commands.
TOPFIND_COMMANDS = say /topfind, say_team /topfind

# Statsfind commands.
STATSFIND_COMMANDS = say /statsfind, say_team /statsfind

# Stats commands.
STATS_COMMANDS = say /statsme, say_team /statsme, say /rankstats, say_team /rankstats

# Stats viewer commands.
STATSVIEWER_COMMANDS = say /stats, say_team /stats, say /statslist, say_team /statslist, say /statsviewer, say_team /statsviewer, say /sw, say_team /sw

# XP commands.
XP_COMMANDS = say /xp, say_team /xp, say /level, say_team /level

# Rank commands.
RANK_COMMANDS = say /rank, say_team /rank, say /skill, say_team /skill

# Commands for enabling/disabling the HUD rank status information.
HUDINFO_COMMANDS = say /hudinfo, say_team /hudinfo

# Commands for enabling/disabling the rank info status on each spawn.
RANKINFO_COMMANDS = say /rankinfo, say_team /rankinfo

[XP Rewards]
# List of key words: kill, death, headshot, assist, blind, bomb_plant, bomb_defuse, bomb_explode, team_kill, suicide, t_win, ct_win, t_lose, ct_lose, vip, vip_flags, weapon's name (knife, usp, ak47 etc.), mvp, hostage_not_rescued, vip_assassinated, vip_not_escaped, all_hostages_rescued, vip_escaped, hostage_took, hostage_rescued, hostage_damaged, hostage_killed, vip_killed
# The key word vip gives additional XP to players who have the flags listed in the key word vip_flags.
# Usage: key word = xp (necessary) team_xp (not necessary). For example (bomb_defuse = 10 5) will give 15 XP to you (10 + 5) and 5 XP to your teammates.
# The values of the key words headshot, assist, weapon's name and vip will add up to the value of kill (example: kill = 5, headshot = 3 and blind = 2 will give 10 XP on blinded Headshot).
# The following key words are available if the system runs on ZP mode: zp_became_survivor, zp_cured, zp_became_nemesis, zp_infected, zp_infect_player, zp_last_human, zp_last_zombie, zp_zombie_win, zp_human_win, zp_survived

kill = 1
headshot = 2
assist = 1
knife = 3
grenade = 1
blind = 1
bomb_plant = 5 2
bomb_defuse = 10 2
bomb_explode = 10 2
team_kill = -2
suicide = -2
vip = 1
vip_flags = t