[Ranks]
# Usage: rank name = required XP
# The amount of ranks is unlimited.

Unranked = 0
Silver I = 2816
Silver II = 3730
Silver III = 4207
Silver IV = 4698
Silver Elite = 4999
Silver Elite Master = 5622
Gold Nova I = 6492
Gold Nova II = 7416
Gold Nova III = 8376
Gold Nova Master = 9348
Master Guardian = 9999
Master Guradian II = 10894
Master Guardian Elite = 12013
Distinguished Master Guardian = 13088
Legendary Eagle = 14187
Legendary Eagle Master = 15495
Supreme Master First Class = 18006
Global Elite = 30000

[Skills]
# Usage: skill name = skill range
# The amount of skills is unlimited.
# Adding '*' against a specific skill, will make new players start with this skill by default.

L- = 0.00
L = 60.00
L+ = 75.00
M- = 85.00
M = 100.00 *
M+ = 115.00
H- = 130.00
H = 140.00
H+ = 150.00
P- = 165.00
P = 180.00
P+ = 195.00
G = 210.00

[Top15]
# Top15 MOTD settings.
# Use 'default' for setting's default value.

TOP15_BACKGROUND = default
TOP15_PRIMARY_COLOR = default
TOP15_SECONDARY_COLOR = default
TOP15_ID_COLOR = default
TOP15_WEAPON_COLOR = default
TOP15_PAGE_COLOR = default
TOP15_SEARCH_COLOR = default

[Rankstats]
# Rankstats MOTD settings.
# Use 'default' for setting's default value.

RANKSTATS_SHOW_CITY = yes
RANKSTATS_BACKGROUND = default
RANKSTATS_PRIMARY_COLOR = default
RANKSTATS_SECONDARY_COLOR = default
RANKSTATS_TERTIARY_COLOR = default
RANKSTATS_QUATERNARY_COLOR = default
RANKSTATS_HEADER_COLOR = default
RANKSTATS_RANK_PROGRESS_COLOR = default

[Mapend]
# MapEnd MOTD settings.
# Use 'default' for setting's default value.

MAPEND_BACKGROUND = default
MAPEND_MAP_COLOR = default
MAPEND_TEAM1_COLOR = #ff4040
MAPEND_TEAM2_COLOR = #42B2FB
MAPEND_CELL_COLOR = default
MAPEND_ID_COLOR = default
MAPEND_STATS_HEADER_COLOR = #dcdcdc
MAPEND_STATS_PRIMARY_COLOR = default
MAPEND_STATS_SECONDARY_COLOR = default

[Name Colors]
# Here you can add players with specific flags to have a different color.
# Syntax: <flags> = <color>
# The setting 'default_name' determines the default's name color.

default_name = white
abcdefghij = red
acd = #32cd32
b = orange

[Skill Colors]
# Here you can make the skills, that are added in the `rank_system_ultimate.ini` config file, under the [Skills] section, have a specific color.
# Syntax: <skill name> = <color>
# The setting 'default_skill' determines the default's name color.

default_skill = #b8a365
L- = #FCE590
L = #FCE590
L+ = #FCE590
M- = #FFC900
M = #FFC900
M+ = #FFC900
H- = #F2880F
H = #F2880F
H+ = #F2880F
P- = #FF3333
P = #FF3333
P+ = #FF3333
G = #000

[XP Colors]
# This setting determines the XP color in /top15 for each player, based on how much XP they have.
# Usage: <xp> = <color>

0 = #E1D9D1
5000 = #8BBCE6
10000 = #6A80E4
15000 = #BD6DFA
20000 = #E315F1
25000 = #E94A46
30000 = #FBD701

[Rank Images]
# Here you can add/change the ranks images by linking the specific rank to the desired rank image's url.
# It's highly advisable that every linked image is a .png format and has dimensions that would match perfectly for non-steam CS (recommended dimensions are 60x24).
# Note that instead of the rank's name, you need to simply write the rank's number, following the order of all ranks under the [Ranks] section in `rank_system_ultimate.ini`.
# Use 'default' for setting's default value.
# Syntax: <rank number> = <image link>

1 = default
2 = default
3 = default
4 = default
5 = default
6 = default
7 = default
8 = default
9 = default
10 = default
11 = default
12 = default
13 = default
14 = default
15 = default
16 = default
17 = default
18 = default
19 = default